blank_issues_enabled: false
contact_links:
  - name: Public GitHub Discussions
    url: https://github.com/python-discord/forms-backend/discussions
    about: GitHub Discussions from external collaborators.
